/**
 * @typedef {{
 *  lt: string,
 *  rt: string,
 *  lb: string,
 *  rb: string,
 *  t: string,
 *  b: string,
 *  l: string,
 *  r: string,
 *}} BorderType
 */
/**
 * @enum {BorderType}
 */
export const Border = {
      Double: {
            lt: "╔",
            rt: "╗",
            lb: "╚",
            rb: "╝",
            t: "═",
            b: "═",
            l: "║",
            r: "║",
      },
      Solid: {
            lt: "┌",
            rt: "┐",
            lb: "└",
            rb: "┘",
            t: "─",
            b: "─",
            l: "│",
            r: "│",
      },
      SolidHorizontal: {
            lt: "─",
            rt: "─",
            lb: "─",
            rb: "─",
            t: "─",
            b: "─",
            l: "",
            r: "",
      },
      SolidTop: {
            lt: "",
            rt: "",
            lb: "",
            rb: "",
            t: "_",
            b: "",
            l: "",
            r: "",
      },
      SolidRound: {
            lt: "╭",
            rt: "╮",
            lb: "╰",
            rb: "╯",
            t: "─",
            b: "─",
            l: "│",
            r: "│",
      },
      SolidBold: {
            lt: "┏",
            rt: "┓",
            lb: "┗",
            rb: "┛",
            t: "━",
            b: "━",
            l: "┃",
            r: "┃",
      },
      Pointed: {
            lt: "┌",
            rt: "┐",
            lb: "└",
            rb: "┘",
            t: "┈",
            b: "┈",
            l: "┊",
            r: "┊"
      },
      PointedRound: {
            lt: "╭",
            rt: "╮",
            lb: "╰",
            rb: "╯",
            t: "┈",
            b: "┈",
            l: "┊",
            r: "┊",
      },
      PointedBold: {
            lt: "┏",
            rt: "┓",
            lb: "┗",
            rb: "┛",
            t: "┉",
            b: "┉",
            l: "┋",
            r: "┋",
      },
      Dashed: {
            lt: "┌",
            rt: "┐",
            lb: "└",
            rb: "┘",
            t: "┄",
            b: "┄",
            l: "┆",
            r: "┆",
      },
      DashedRound: {
            lt: "╭",
            rt: "╮",
            lb: "╰",
            rb: "╯",
            t: "┄",
            b: "┄",
            l: "┆",
            r: "┆",
      },
      DashedBold: {
            lt: "┏",
            rt: "┓",
            lb: "┗",
            rb: "┛",
            t: "┅",
            b: "┅",
            l: "┇",
            r: "┇",
      },
      BigDash: {
            lt: "┌",
            rt: "┐",
            lb: "└",
            rb: "┘",
            t: "╌",
            b: "╌",
            l: "╎",
            r: "╎",
      },
      BigDashBold: {
            lt: "┏",
            rt: "┓",
            lb: "┗",
            rb: "┛",
            t: "╍",
            b: "╍",
            l: "╏",
            r: "╏",
      },
      Black: {
            lt: "▛",
            rt: "▜",
            lb: "▙",
            rb: "▟",
            t: "▃",
            b: "▃",
            l: "▌",
            r: "▌",
      },
      Hashtag: {
            lt: "#",
            rt: "#",
            lb: "#",
            rb: "#",
            t: "#",
            b: "#",
            l: "#",
            r: "#",
      },
      LightShade: {
            lt: "░",
            rt: "░",
            lb: "░",
            rb: "░",
            t: "░",
            b: "░",
            l: "░",
            r: "░",
      },
      MediumShade: {
            lt: "▒",
            rt: "▒",
            lb: "▒",
            rb: "▒",
            t: "▒",
            b: "▒",
            l: "▒",
            r: "▒",
      },
      BoldShade: {
            lt: "▓",
            rt: "▓",
            lb: "▓",
            rb: "▓",
            t: "▓",
            b: "▓",
            l: "▓",
            r: "▓",
      },
      None: undefined,
}