// Generated by dts-bundle-generator v9.5.1

export type Position = {
	x: number;
	y: number;
	onMove(callback: (pos: Position) => void): () => void;
};
export type PhysicsPosition = {
	x: number;
	y: number;
	vx: number;
	vy: number;
	ax: number;
	ay: number;
	onMove(callback: (pos: Position) => void): () => void;
};
/**
 * x should be considered the leftmost
 * point onto the rectangle, while y should be considered
 * the topmost point onto the rectangle.
 * ### example
 *
 * ---
 * \
 * ```plaintext
 * a +---+ b
 *   |   |
 * c +---+ d
 * ```
 *
 * `c` is the (x,y) point used to check conditions
 */
export type RigidBody = {
	tag: string[];
	x: number;
	y: number;
	width: number;
	height: number;
	onCollision(watcher: (body: RigidBody) => void): () => void;
	triggerCollision(body: RigidBody): void;
};
declare class Camera {
	/**
	 * @param {WebGLRenderingContext} gl
	 */
	constructor(gl: WebGLRenderingContext);
	focus: number;
	x: number;
	y: number;
	rotation: number;
	/**
	 * bind the camera to the specified program.
	 * @param {WebGLProgram} program - program to bound
	 * @param {string} name - name of the uniform used inside the program
	 * to represent the camera
	 */
	bind(program: WebGLProgram, name: string): void;
	/**
	 * follow a position onto the screen
	 * @param {Position} position
	 */
	follow(position: Position): void;
	#private;
}
export type Entity<T extends {}> = {
	add<K extends {}>(component: K): Entity<T & K>;
	has(key: string): boolean;
} & T;
/**
 * @template {{}} T
 * @typedef {{
 *    add<K extends {}>(component: K): Entity<T & K>,
 *    has(key: string): boolean,
 * } & T} Entity
 */
/**
 * @template {{}} K
 * @return {Entity<K>}
 */
export declare function createEntity<K extends {}>(): Entity<K>;
export type System<T> = {
	add(comp: T): void;
	delete(comp: T): void;
	dispose(): void;
	stop(): void;
	resume(): void;
};
/**
 * @param system function that will be executed
 * as a lower priority task
 */
export declare function createSystem<T>(system: (components: T[], isDirty: boolean) => void): System<T>;
export declare function createAnimationSystem<T>(system: (components: T[], isDirty: boolean) => void): System<T>;
export declare class Scene {
	/**
	 * add an entity to the scene.
	 * @param {Entity<unknown>} entity
	 */
	add(entity: Entity<Record<string, unknown>>): void;
	/**
	 * add system to the scene. If the scene
	 * is stopped and later resumed, all systems
	 * are restarted
	 * @param {System<unknown>} system
	 */
	use(system: System<unknown>): void;
	/**
	 * stop the current scene and remove all
	 * drawn entities from the screen. The entities are
	 * preserved for later reuse, in case the scene will be
	 * resumed with {@link Scene.resume()}
	 */
	stop(): void;
	/**
	 * resume all the systems that where
	 * registered and add all {@link GPUEntity2D}
	 * that where drawn when the scene was
	 * removed
	 */
	resume(): void;
	/**
	 * remove all entities from the screen and
	 * stop al the systems available.
	 * if the scene is resumed, nothing will be preserved
	 */
	clear(): void;
	/**
	 * @param {() => void} callback
	 */
	onResume(callback: () => void): () => boolean;
	/**
	 * @param {() => void} callback
	 */
	onStop(callback: () => void): () => boolean;
	/**
	 * @param {() => void} callback
	 */
	onClear(callback: () => void): () => boolean;
	#private;
}
export declare class SceneManager {
	current: Scene;
	/**
	 * @param {() => Scene} scene - scene builder.
	 * @param {boolean} [resumable=true] - tells to the manager if the
	 * scene could be later resumed instead of being recreated. this is useful
	 * for stateful scenes like when you stop the game to open a menu and later
	 * on resume it.
	 * ## note
	 * ---
	 * is important the reuse of same builder,
	 * because if you change it
	 * the manager can't tell if the scene was already created and must
	 * be resumed, so it creates new one instead.
	 *
	 * @example
	 * ```javascript
	 * ❌ NO
	 * function MyScene() {...}
	 * manager.use(() => MyScene())
	 * manager.use(() => MyScene()) // not resumed
	 *
	 * ✅ OK
	 * function MyScene() {...}
	 * manager.use(MyScene)
	 * manager.use(MyScene)
	 * ```
	 */
	use(scene: () => Scene, resumable?: boolean): void;
	#private;
}
declare class GPUEntity2D {
	x: number;
	y: number;
	scaleY: number;
	scaleX: number;
	rotation: number;
	light: number;
	/**
	 * @abstract
	 * @param {GPUContext} ctx
	 */
	draw(ctx: GPUContext): void;
	/**
	 * @abstract
	 * @param {GPUContext} ctx
	 */
	remove(ctx: GPUContext): void;
}
declare class Shape extends GPUEntity2D {
	/**
	 *
	 * @param {number[]} vertices
	 */
	constructor(vertices: number[]);
	/**
	 * @type {number[]}
	 */
	vertices: number[];
	/**
	 * color used to draw each vertex.
	 * must be a series of numbers following scheme `[r,g,b,a]`
	 * repeated for each vertex
	 * @type {number[]}
	 */
	colors: number[];
	/**
	 * accepted values are:
	 *    - `3` for triangles primitive
	 *    - `2` for lines
	 *    - `1` for points
	 * @type {1 | 2 | 3}
	 */
	primitive: 1 | 2 | 3;
	zIndex: number;
	coords: number[];
	indices: number[];
	#private;
}
declare class TextureEntity extends GPUEntity2D {
	/**
	 * @type {string}
	 */
	image: string;
	zIndex: number;
	textureCoords: number[];
	vertices: number[];
	indices: number[];
	startX: number;
	startY: number;
	endX: number;
	endY: number;
	#private;
}
/**
 * Represents the rendering context for WebGL operations.
 */
export interface GPUContext {
	camera: Camera;
	entities: GPUEntity2D[];
	/**
	 * Draws all entities added to the current context
	 */
	draw(): void;
	/**
	 * Clears the canvas
	 */
	clear(): void;
	/**
	 * Creates a rectangle shape that
	 * can be later drawn using
	 * {@link GPUContext.drawShape()}
	 */
	rect(): Shape;
	/**
	 * Adds specified shape to the screen.
	 * @param shape - The shape to add.
	 */
	drawShape(shape: Shape): void;
	/**
	 * Removes specified shape from the screen
	 * @param shape - The shape to remove.
	 */
	clearShape(shape: Shape): void;
	/**
	 * Creates a new texture entity.
	 * @returns {TextureEntity} A new texture entity.
	 */
	image(): TextureEntity;
	/**
	 * Adds a texture entity to the texture bucket for rendering.
	 * @param {TextureEntity} img - The texture entity to add.
	 */
	drawImage(img: TextureEntity): void;
	/**
	 * Removes specified texture entity from the screen
	 * @param img - The texture entity to remove.
	 */
	clearImage(img: TextureEntity): void;
	/**
	 * remove all current drawn entities.
	 */
	removeAll(): void;
}
/**@import {System} from "../components/index.js" */
/**@import GPUEntity2D from "../rendering/shader/entity/GPUEntity2D.js" */
/**@import GPUContext from "../rendering/index.js" */
export class Game {
	static "__#16@#game": Game;
	static get(): Game;
	/**
	 * the camera used inside the scene.
	 * every default entity is bound to this
	 * camera.
	 */
	camera(): Camera;
	/**
	 * Context used to draw entities onto the canvas.
	 * To render an entity, it must be created with the
	 * context and then added to the {@link Game.engine}, like the example
	 * below
	 * @example
	 * ```javascript
	 * const game = useGame();
	 * const img = game.ctx.image();
	 * game.engine.add(img);
	 * ```
	 */
	ctx: GPUContext;
	/**
	 * system that renders each entity onto the screen.
	 * it works, under the hood, with {@link Game.ctx}
	 * to render every entity that was added
	 */
	engine: System<GPUEntity2D>;
	/**
	 * scene manager useful to transit across scenes
	 * and preserve their state
	 */
	scenes: SceneManager;
	#private;
}
export function useGame(): Game;
export function usePosition(): Position;
export function usePhysicsPosition(): PhysicsPosition;
export function usePhysicsSystem(): System<PhysicsPosition>;
declare class Texture {
	/**
	 * @param {WebGLRenderingContext} gl
	 * @param {string} name
	 * @param {WebGLProgram} program
	 */
	constructor(gl: WebGLRenderingContext, name: string, program: WebGLProgram);
	image: string;
	/**
	 *
	 * @param {string} value
	 */
	write(value: string): void;
	bind(): void;
	#private;
}
export function useSprite(asset: string): {
	sprite: Texture;
	/**
	 * bind the position component
	 * to the sprite, so whenever the
	 * position component changes the sprite
	 * will follow it. Every position that
	 * was previously bind will be unbind
	 * @param {Position} position
	 */
	bind(position: Position): void;
	/**
	 * detach previously bound
	 * position.
	 * @throws {Error} if no position was bound
	 */
	unbind(): void;
	/**
	 * stop rendering the sprite onto
	 * the screen
	 */
	hide(): void;
	/**
	 * start rendering the sprite onto the
	 * screen
	 */
	show(): void;
};
/**
 * create a collision system where,
 * each body registered to it, is checked
 * to see whether is colliding with
 * something else, in that case triggers
 * an event of collision
 * @returns {System<RigidBody>}
 */
export function useCollisionSystem(): System<RigidBody>;
export function useInput(scene: Scene): {
	/**
	 * set an event handler attached
	 * to an abstract event.
	 * @param {string} event
	 * @param {() => void} handler
	 */
	on: (event: string, handler: () => void) => () => boolean;
	/**
	 * map an abstract event onto a key.
	 * @param {string} ev
	 * @param {string} key
	 */
	addMapping: (ev: string, key: string) => void;
	/**
	 * remove previously set mapping
	 * @param {string} key
	 */
	removeMapping: (key: string) => void;
};
export function useBody(tag?: string[]): RigidBody;
export function useScene(): Scene;
