// Generated by dts-bundle-generator v9.5.1

export type Position = {
	x: number;
	y: number;
	onMove(callback: (pos: Position) => void): () => void;
};
/**
 * x should be considered the leftmost
 * point onto the rectangle, while y should be considered
 * the topmost point onto the rectangle.
 * ### example
 *
 * ---
 * \
 * ```plaintext
 * a +---+ b
 *   |   |
 * c +---+ d
 * ```
 *
 * `c` is the (x,y) point used to check conditions
 */
export type RigidBody = {
	x: number;
	y: number;
	width: number;
	height: number;
	onCollision(watcher: (body: RigidBody) => void): () => void;
	triggerCollision(body: RigidBody): void;
};
export type PhysicsPosition = {
	x: number,
	y: number,
	vx: number,
	vy: number,
	ax: number,
	ay: number,
	onMove(callback: (pos: Position) => void): () => void;
}
declare class Camera {
	/**
	 * @param {WebGLRenderingContext} gl
	 */
	constructor(gl: WebGLRenderingContext);
	focus: number;
	x: number;
	y: number;
	rotation: number;
	/**
	 * bind the camera to the specified program.
	 * @param {WebGLProgram} program - program to bound
	 * @param {string} name - name of the uniform used inside the program
	 * to represent the camera
	 */
	bind(program: WebGLProgram, name: string): void;
	/**
	 * follow a position onto the screen
	 * @param {Position} position
	 */
	follow(position: Position): void;
	#private;
}
declare class Shape extends GPUEntity2D {
	/**
	 *
	 * @param {number[]} vertices
	 */
	constructor(vertices: number[]);
	/**
	 * @type {number[]}
	 */
	vertices: number[];
	/**
	 * color used to draw each vertex.
	 * must be a series of numbers following scheme `[r,g,b,a]`
	 * repeated for each vertex
	 * @type {number[]}
	 */
	colors: number[];
	/**
	 * accepted values are:
	 *    - `3` for triangles primitive
	 *    - `2` for lines
	 *    - `1` for points
	 * @type {1 | 2 | 3}
	 */
	primitive: 1 | 2 | 3;
	zIndex: number;
	coords: number[];
	indices: number[];
	#private;
}
/**
 * Represents the rendering context for WebGL operations.
 */
export interface GPUContext {
	camera: Camera;
	entities: GPUEntity2D[];
	/**
	 * Draws all entities added to the current context
	 */
	draw(): void;
	/**
	 * Clears the canvas
	 */
	clear(): void;
	/**
	 * Creates a rectangle shape that
	 * can be later drawn using
	 * {@link GPUContext.drawShape()}
	 */
	rect(): Shape;
	/**
	 * Adds specified shape to the screen.
	 * @param shape - The shape to add.
	 */
	drawShape(shape: Shape): void;
	/**
	 * Removes specified shape from the screen
	 * @param shape - The shape to remove.
	 */
	clearShape(shape: Shape): void;
	/**
	 * Creates a new texture entity.
	 * @returns {TextureEntity} A new texture entity.
	 */
	image(): TextureEntity;
	/**
	 * Adds a texture entity to the texture bucket for rendering.
	 * @param {TextureEntity} img - The texture entity to add.
	 */
	drawImage(img: TextureEntity): void;
	/**
	 * Removes specified texture entity from the screen
	 * @param img - The texture entity to remove.
	 */
	clearImage(img: TextureEntity): void;
	/**
	 * remove all current drawn entities.
	 */
	removeAll(): void;
}
declare class GPUEntity2D {
	x: number;
	y: number;
	scaleY: number;
	scaleX: number;
	rotation: number;
	light: number;
	/**
	 * @abstract
	 * @param {GPUContext} ctx
	 */
	draw(ctx: GPUContext): void;
	/**
	 * @abstract
	 * @param {GPUContext} ctx
	 */
	remove(ctx: GPUContext): void;
}
declare class TextureEntity extends GPUEntity2D {
	/**
	 * @type {string}
	 */
	image: string;
	zIndex: number;
	textureCoords: number[];
	vertices: number[];
	indices: number[];
	startX: number;
	startY: number;
	endX: number;
	endY: number;
	#private;
}
export function createEntity<K extends {}>(): Entity<K>;
export type Entity<T extends {}> = {
	add: <V extends string, X extends {}>(component: Component<V, X>) => Entity<T & {
		[K in V]: X;
	}>;
} & T;
export type Component<T extends string, K extends {}> = {
	$$name: T;
	state: K;
};
export type Query<K extends string, T extends {}> = (e: Entity<{}>) => e is Entity<T>;
declare const sprite: Query<"sprite", {
	sprite: TextureEntity;
	/**
	 * bind the position component
	 * to the sprite, so whenever the
	 * position component changes the sprite
	 * will follow it. Every position that
	 * was previously bind will be unbind
	 * @param {Position} position
	 */
	bind(position: Position): void;
	/**
	 * detach previously bound
	 * position.
	 * @throws {Error} if no position was bound
	 */
	unbind(): void;
}>;
export declare const useSprite: (asset: string) => Component<"sprite", {
	sprite: TextureEntity;
	/**
	 * bind the position component
	 * to the sprite, so whenever the
	 * position component changes the sprite
	 * will follow it. Every position that
	 * was previously bind will be unbind
	 * @param {Position} position
	 */
	bind(position: Position): void;
	/**
	 * detach previously bound
	 * position.
	 * @throws {Error} if no position was bound
	 */
	unbind(): void;
}>;
declare const position: Query<"position", {
	x: number;
	y: number;
	/**
	 *
	 * @param {(pos: Position) => void} callback
	 * @returns {() => void} - unsubscribe method
	 */
	onMove(callback: (pos: Position) => void): () => void;
}>;
export declare const usePosition: () => Component<"position", {
	x: number;
	y: number;
	/**
	 *
	 * @param {(pos: Position) => void} callback
	 * @returns {() => void} - unsubscribe method
	 */
	onMove(callback: (pos: Position) => void): () => void;
}>;
/**
 * create a collision system where,
 * each body registered to it, is checked
 * to see whether is colliding with
 * something else, in that case triggers
 * an event of collision
 */
export function useCollisionSystem(): void;
declare const body: Query<"body", RigidBody>;
export declare const useBody: () => Component<"body", RigidBody>;
declare const physics: Query<"physics", {
	x: number;
	y: number;
	vx: number;
	vy: number;
	ax: number;
	ay: number;
	/**
	 *
	 * @param {(pos: PhysicsPosition) => void} callback
	 * @returns {() => void} - unsubscribe method
	 */
	onMove(callback: (pos: PhysicsPosition) => void): () => void;
}>;
export declare const usePhysics: () => Component<"physics", {
	x: number;
	y: number;
	vx: number;
	vy: number;
	ax: number;
	ay: number;
	/**
	 *
	 * @param {(pos: PhysicsPosition) => void} callback
	 * @returns {() => void} - unsubscribe method
	 */
	onMove(callback: (pos: PhysicsPosition) => void): () => void;
}>;
export function usePhysicsSystem(): void;
/**
 * class that handles world.
 * world are micro-cosmos, composed
 * of entities and systems
 * that acts only on that entities.
 * only one world can exist at time
 */
export class World {
	entities: Entity<{}>[];
	/**
	 * add new entity into the world.
	 * from the moment an entity is added,
	 * until it is removed with {@link World.remove()},
	 * the entity will be affected to systems
	 * that can query it.
	 * @param {Entity<{}>} entity
	 */
	add(entity: Entity<{}>): void;
	/**
	 * remove the specified entity from the world
	 * @param {Entity<{}>} entity
	 */
	remove(entity: Entity<{}>): void;
	/**
	 * add system to the tracked once.
	 * A system that is tracked is dependant
	 * to the World for its execution
	 * @param {() => void} system
	 */
	addSystem(system: () => void, priority?: number): void;
	/**
	 * cleanup method called
	 * when the World leave
	 */
	onLeave(): void;
	/**
	 * method used when the World
	 * is started. All systems attached to it are
	 * restarted
	 */
	onEnter(): void;
	/**
	 * lifecycle hook called each time an
	 * entity is added or removed from the system
	 * @param {() => void} hook
	 */
	onStateChange(hook: () => void): () => boolean;
	/**
	 * @param {() => void} callback
	 */
	onResume(callback: () => void): () => boolean;
	/**
	 * @param {() => void} callback
	 */
	onStop(callback: () => void): () => boolean;
	#private;
}
/**@import {World} from "./World" */
/**
 * class that handles {@link World} lifecycle.
 */
export class WorldManager {
	/**
	 * current world in execution
	 * @type {World}
	 */
	static "__#1@#current": World;
	/**
	 * change the current world.
	 * stopping previous systems and
	 * replacing all old entities.
	 * they will remain in the old world,
	 * that can be later resumed
	 * @param {World} world
	 */
	static use(world: World): void;
	/**
	 * current world in execution
	 */
	static current: World;
}
/**@import GPUEntity2D from "../rendering/shader/entity/GPUEntity2D.js" */
/**@import GPUContext from "../rendering/index.js" */
export class Game {
	static "__#14@#game": Game;
	static get(): Game;
	/**
	 * the camera used inside the scene.
	 * every default entity is bound to this
	 * camera.
	 */
	camera: Camera;
	/**
	 * Context used to draw entities onto the canvas.
	 * To render an entity, it must be created with the
	 * context and then drawn using standard Context api.
	 * this is simplified by the `useSprite` hook. if
	 * you want more control, you have to do something like
	 * this
	 * @example
	 * ```javascript
	 * const game = useGame();
	 * const img = game.ctx.image();
	 * img.draw(game.ctx);
	 * const f = () => {
	 *    game.ctx.clear();
	 *    game.ctx.draw();
	 *    requestAnimationFrame(f);
	 * }
	 * f();
	 * ```
	 */
	ctx: GPUContext;
	/**
	 * scene manager useful to transit across Worlds
	 * and preserve their state
	 */
	worlds: typeof WorldManager;
	/**
	 * method used to preload all images
	 * that will be used inside the game
	 * @param  {Record<string,string>} imgs
	 */
	preload(imgs: Record<string, string>): Promise<void>;
	#private;
}
export function useGame(): Game;
export function useSystem<K extends string, U extends {}, Q extends Query<K, U>[]>(update: (entity: Entity<Union<Q>>) => void, ...query: Q): void;
export type Union<Q extends unknown[]> = Q extends [
	infer X,
	...infer Y
] ? (X extends Query<infer R, infer N> ? Record<R, N> : {}) & Union<Y> : {};
export function useInput(): {
	/**
	 * set an event handler attached
	 * to an abstract event.
	 * @param {string} event
	 * @param {() => void} handler
	 */
	on: (event: string, handler: () => void) => () => boolean;
	/**
	 * map an abstract event onto a key.
	 * @param {string} ev
	 * @param {string} key
	 */
	addMapping: (ev: string, key: string) => void;
	/**
	 * remove previously set mapping
	 * @param {string} key
	 */
	removeMapping: (key: string) => void;
};
declare class TaskManager {
	/**
	 * @type {TaskManager}
	 */
	static "__#16@#instance": TaskManager;
	static get(): TaskManager;
	/**
	 * @param {() => void} task
	 */
	addTask(task: () => void): () => void;
	/**
	 * creates an high priority task that
	 * runs before each frame
	 * @param {() => void} task
	 */
	addAnimationTask(task: () => void): () => void;
	/**
	 * Clears all tasks and animations from the task manager.
	 */
	clearAll(): void;
	#private;
}
/**
 * Provides access to the TaskManager singleton instance.
 * @returns {TaskManager} The TaskManager instance.
 */
export function useTaskManager(): TaskManager;
/**
 * Initializes the rendering context for WebGL operations.
 */
export function useRendering(): void;

declare namespace Query$1 {
    /**
     * Query for sprite components.
     */
    export { sprite };

    /**
     * Query for position components.
     */
    export { position };

    /**
     * Query for body components.
     */
    export { body };

    /**
     * Query for physics components.
     */
    export { physics };
}

/**
 * Initializes and provides access to a new World instance.
 * @returns {World} The newly created World instance.
 */
export function useWorld(): World;

export {
    Query$1 as Query,
};

